[project]
name = "python-project-template"
version = "0.1.0"
description = "Python Project Template"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "fastapi[standard]>=0.118.0",
    "pydantic>=2.11.10",
    "pydantic-settings>=2.11.0",
]

[dependency-groups]
dev = ["pytest>=8.4.2"]

[tools.pytest.ini_options]
pythonpath = "."
